In [2]:
import pandas as pd
import numpy as np
premier_league_result = pd.read_csv("results.csv")
premier_league_stat = pd.read_csv("stats.csv")

premier_league_result.sample(50)

,home_team,away_team,home_goals,away_goals,result,season
2234,Arsenal,Wigan Athletic,1.0,2.0,A,2011-2012
231,Middlesbrough,Bolton Wanderers,5.0,1.0,H,2006-2007
714,Sunderland,Manchester City,1.0,2.0,A,2007-2008
757,Tottenham Hotspur,Liverpool,0.0,2.0,A,2007-2008
1581,Birmingham City,Everton,0.0,2.0,A,2010-2011
2704,West Ham United,Everton,2.0,3.0,A,2013-2014
2055,Queens Park Rangers,Manchester United,0.0,2.0,A,2011-2012
3915,Sunderland,Hull City,3.0,0.0,H,2016-2017
383,Everton,Wigan Athletic,2.0,1.0,H,2007-2008
1977,Arsenal,Sunderland,2.0,1.0,H,2011-2012
2691,Aston Villa,Newcastle United,1.0,2.0,A,2013-2014
1080,Middlesbrough,Fulham,0.0,0.0,D,2008-2009
847,West Ham United,Arsenal,0.0,2.0,A,2008-2009
451,Sunderland,Blackburn Rovers,1.0,2.0,A,2007-2008
4512,Manchester United,West Bromwich Albion,0.0,1.0,A,2017-2018
1982,Newcastle United,Wigan Athletic,1.0,0.0,H,2011-2012
2020,Bolton Wanderers,Everton,0.0,2.0,A,2011-2012
4364,Southampton,Huddersfield Town,1.0,1.0,D,2017-2018
1695,Manchester United,Sunderland,2.0,0.0,H,2010-2011
2732,Chelsea,Cardiff City,4.0,1.0,H,2013-2014
4309,Huddersfield Town,Manchester City,1.0,2.0,A,2017-2018
3168,Southampton,Manchester City,0.0,3.0,A,2014-2015
2875,West Ham United,Newcastle United,1.0,3.0,A,2013-2014
557,Newcastle United,Derby County,2.0,2.0,D,2007-2008
3099,Stoke City,Newcastle United,1.0,0.0,H,2014-2015
4097,Arsenal,West Ham United,3.0,0.0,H,2016-2017
2201,Fulham,Norwich City,2.0,1.0,H,2011-2012
43,Chelsea,Liverpool,1.0,0.0,H,2006-2007
2450,Manchester City,Reading,1.0,0.0,H,2012-2013
4514,Brighton and Hove Albion,Tottenham Hotspur,1.0,1.0,D,2017-2018
2263,Bolton Wanderers,West Bromwich Albion,2.0,2.0,D,2011-2012
1756,Manchester United,Aston Villa,3.0,1.0,H,2010-2011
3976,Swansea City,West Ham United,1.0,4.0,A,2016-2017
3286,Southampton,West Ham United,0.0,0.0,D,2014-2015
1785,West Bromwich Albion,Wolverhampton Wanderers,1.0,1.0,D,2010-2011
2453,Tottenham Hotspur,Stoke City,0.0,0.0,D,2012-2013
4341,Crystal Palace,Watford,2.0,1.0,H,2017-2018
1934,Wolverhampton Wanderers,Tottenham Hotspur,0.0,2.0,A,2011-2012
160,Middlesbrough,Wigan Athletic,1.0,1.0,D,2006-2007
1647,Stoke City,Liverpool,2.0,0.0,H,2010-2011
1790,Newcastle United,Bolton Wanderers,1.0,1.0,D,2010-2011
2052,Newcastle United,Swansea City,0.0,0.0,D,2011-2012
1198,Blackburn Rovers,Aston Villa,2.0,1.0,H,2009-2010
2025,West Bromwich Albion,Tottenham Hotspur,1.0,3.0,A,2011-2012
4542,Arsenal,Burnley,5.0,0.0,H,2017-2018
161,Portsmouth,Everton,2.0,0.0,H,2006-2007
1357,Chelsea,Birmingham City,3.0,0.0,H,2009-2010
3623,Chelsea,West Bromwich Albion,2.0,2.0,D,2015-2016
713,Reading,Fulham,0.0,2.0,A,2007-2008
2295,Southampton,Wigan Athletic,0.0,2.0,A,2012-2013

In [37]:

premier_df = premier_league_result.loc[premier_league_result["season"].str.contains("2018")]



# premier_df.sort_values(by="away_team", ascending=True)

In [83]:
premier_df["winner"] = "Draw"
premier_df["loser"] = "Draw"

premier_df.loc[premier_df["home_goals"] > premier_df["away_goals"], "winner"] = premier_df["home_team"]
premier_df.loc[premier_df["home_goals"] < premier_df["away_goals"], "winner"] = premier_df["away_team"]

premier_df.loc[premier_df["home_goals"] < premier_df["away_goals"], "loser"] = premier_df["home_team"]
premier_df.loc[premier_df["home_goals"] > premier_df["away_goals"], "loser"] = premier_df["away_team"]


premier_df["winner"].count()

premier_df.tail(20)

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_24631/4109546904.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  premier_df["winner"] = "Draw"
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_24631/4109546904.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  premier_df["loser"] = "Draw"

,home_team,away_team,home_goals,away_goals,result,season,winner,loser
4540,Everton,Southampton,1.0,1.0,D,2017-2018,Draw,Draw
4541,Manchester City,Huddersfield Town,0.0,0.0,D,2017-2018,Draw,Draw
4542,Arsenal,Burnley,5.0,0.0,H,2017-2018,Arsenal,Burnley
4543,Chelsea,Liverpool,1.0,0.0,H,2017-2018,Chelsea,Liverpool
4544,Swansea City,Southampton,0.0,1.0,A,2017-2018,Southampton,Swansea City
4545,Chelsea,Huddersfield Town,1.0,1.0,D,2017-2018,Draw,Draw
4546,Leicester City,Arsenal,3.0,1.0,H,2017-2018,Leicester City,Arsenal
4547,Manchester City,Brighton and Hove Albion,3.0,1.0,H,2017-2018,Manchester City,Brighton and Hove Albion
4548,Tottenham Hotspur,Newcastle United,1.0,0.0,H,2017-2018,Tottenham Hotspur,Newcastle United
4549,West Ham United,Manchester United,0.0,0.0,D,2017-2018,Draw,Draw
4550,Burnley,AFC Bournemouth,1.0,2.0,A,2017-2018,AFC Bournemouth,Burnley
4551,Crystal Palace,West Bromwich Albion,2.0,0.0,H,2017-2018,Crystal Palace,West Bromwich Albion
4552,Huddersfield Town,Arsenal,0.0,1.0,A,2017-2018,Arsenal,Huddersfield Town
4553,Liverpool,Brighton and Hove Albion,4.0,0.0,H,2017-2018,Liverpool,Brighton and Hove Albion
4554,Manchester United,Watford,1.0,0.0,H,2017-2018,Manchester United,Watford
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018,Newcastle United,Chelsea
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018,Manchester City,Southampton
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018,Stoke City,Swansea City
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018,Tottenham Hotspur,Leicester City
4559,West Ham United,Everton,3.0,1.0,H,2017-2018,West Ham United,Everton

In [93]:
premier_df

,home_team,away_team,home_goals,away_goals,result,season,winner,loser
4180,NaN,Leicester City,4.0,3.0,H,2017-2018,Arsenal,Leicester City
4181,NaN,Liverpool,3.0,3.0,D,2017-2018,Draw,Draw
4182,NaN,Burnley,2.0,3.0,A,2017-2018,Burnley,Chelsea
4183,NaN,Huddersfield Town,0.0,3.0,A,2017-2018,Huddersfield Town,Crystal Palace
4184,NaN,Stoke City,1.0,0.0,H,2017-2018,Everton,Stoke City
...,...,...,...,...,...,...,...,...
4555,NaN,Chelsea,3.0,0.0,H,2017-2018,Newcastle United,Chelsea
4556,NaN,Manchester City,0.0,1.0,A,2017-2018,Manchester City,Southampton
4557,NaN,Stoke City,1.0,2.0,A,2017-2018,Stoke City,Swansea City
4558,NaN,Leicester City,5.0,4.0,H,2017-2018,Tottenham Hotspur,Leicester City
4559,NaN,Everton,3.0,1.0,H,2017-2018,West Ham United,Everton

In [ ]:
equation = np.array([[2, -3], [1, 1]])
answer = np.array([[4, 12]])



equation_inverse = np.linalg.inv(equation)

equation_inverse
equation_inverse @ answer.transpose()

array([[8.],
       [4.]])

In [ ]:
import pandas as pd
import numpy as np
premier_league_result = pd.read_csv("results.csv")
premier_league_stat = pd.read_csv("stats.csv")

premier_league_result = premier_league_result.loc[premier_league_result["season"].str.contains("2018")]
premier_league_result

,home_team,away_team,home_goals,away_goals,result,season
4180,Arsenal,Leicester City,4.0,3.0,H,2017-2018
4181,Watford,Liverpool,3.0,3.0,D,2017-2018
4182,Chelsea,Burnley,2.0,3.0,A,2017-2018
4183,Crystal Palace,Huddersfield Town,0.0,3.0,A,2017-2018
4184,Everton,Stoke City,1.0,0.0,H,2017-2018
...,...,...,...,...,...,...
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018
4559,West Ham United,Everton,3.0,1.0,H,2017-2018

In [134]:
premier_league_result = premier_league_result.loc[premier_league_result["season"].str.contains("2018")]
premier_league_result

,home_team,away_team,home_goals,away_goals,result,season
4180,Arsenal,Leicester City,4.0,3.0,H,2017-2018
4181,Watford,Liverpool,3.0,3.0,D,2017-2018
4182,Chelsea,Burnley,2.0,3.0,A,2017-2018
4183,Crystal Palace,Huddersfield Town,0.0,3.0,A,2017-2018
4184,Everton,Stoke City,1.0,0.0,H,2017-2018
...,...,...,...,...,...,...
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018
4559,West Ham United,Everton,3.0,1.0,H,2017-2018

In [140]:
home = premier_league_result[["home_team", "result"]]
home["club"] = home["home_team"]
home["outcome"] = home["result"].map({
    "D": "Draw",
    "H": "Win",
    "A": "Loss"
})
home = home[["club", "outcome"]]


away = premier_league_result[["away_team", "result"]]
away["club"] = away["away_team"]
away["outcome"] = away["result"].map({
    "D": "Draw",
    "H": "Loss",
    "A": "Win"
})

away = away[["club", "outcome"]]

all_results = pd.concat([home, away], ignore_index=True)
all_results

final_premier_league = all_results.pivot_table(columns="outcome", index="club", aggfunc="size")
final_premier_league

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/2832456971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home["club"] = home["home_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/2832456971.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home["outcome"] = home["result"].map({
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/2832456971.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["club"] = away["away_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/2832456971.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["outcome"] = away["result"].map({

outcome                   Draw  Loss  Win
club
AFC Bournemouth             11    16   11
Arsenal                      6    13   19
Brighton and Hove Albion    13    16    9
Burnley                     12    12   14
Chelsea                      7    10   21
Crystal Palace              11    16   11
Everton                     10    15   13
Huddersfield Town           10    19    9
Leicester City              11    15   12
Liverpool                   12     5   21
Manchester City              4     2   32
Manchester United            6     7   25
Newcastle United             8    18   12
Southampton                 15    16    7
Stoke City                  12    19    7
Swansea City                 9    21    8
Tottenham Hotspur            8     7   23
Watford                      8    19   11
West Bromwich Albion        13    19    6
West Ham United             12    16   10

In [142]:
#final_premier_league["points"] = (final_premier_league["Draw"]*1) + (final_premier_league["Win"]*3)
final_premier_league.sum(axis=1)

club
AFC Bournemouth             38
Arsenal                     38
Brighton and Hove Albion    38
Burnley                     38
Chelsea                     38
Crystal Palace              38
Everton                     38
Huddersfield Town           38
Leicester City              38
Liverpool                   38
Manchester City             38
Manchester United           38
Newcastle United            38
Southampton                 38
Stoke City                  38
Swansea City                38
Tottenham Hotspur           38
Watford                     38
West Bromwich Albion        38
West Ham United             38
dtype: int64

In [109]:
home = premier_league_result[["home_team", "home_goals"]]
home['club'] = home["home_team"]
home["goals"] = home["home_goals"]
home = home[["club", "goals"]]

away = premier_league_result[["away_team", "away_goals"]]
away["club"] = away["away_team"]
away["goals"] = away["away_goals"]

away = away[["club", "goals"]]

all_goals = pd.concat([home, away],ignore_index=True)
total_goals = all_goals.pivot_table(index="club", values="goals", aggfunc="sum")

league_table = final_premier_league.merge(total_goals, on="club", how="inner")
league_table.rename(columns={"goals": "GF", "Played": "P", "Draw": "D", "Loss": "L", "Win": "W", "points": "PTS"}, inplace=True)

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/1781757404.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home['club'] = home["home_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/1781757404.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home["goals"] = home["home_goals"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/1781757404.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["club"] = away["away_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/1781757404.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["goals"] = away["away_goals"]

In [101]:
premier_league_result

,home_team,away_team,home_goals,away_goals,result,season
4180,Arsenal,Leicester City,4.0,3.0,H,2017-2018
4181,Watford,Liverpool,3.0,3.0,D,2017-2018
4182,Chelsea,Burnley,2.0,3.0,A,2017-2018
4183,Crystal Palace,Huddersfield Town,0.0,3.0,A,2017-2018
4184,Everton,Stoke City,1.0,0.0,H,2017-2018
...,...,...,...,...,...,...
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018
4559,West Ham United,Everton,3.0,1.0,H,2017-2018

In [105]:
home = premier_league_result[["home_team", "away_goals"]]
home['club'] = home["home_team"]
home["goals"] = home["away_goals"]

home = home[["club", "goals"]]

away = premier_league_result[["away_team", "home_goals"]]
away["club"] = away["away_team"]
away["goals"] = away["home_goals"]

away = away[["club", "goals"]]
away

all_goals = pd.concat([home, away],ignore_index=True)
against_goals = all_goals.pivot_table(index="club", values="goals", aggfunc="sum")
against_goals

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/3475939722.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home['club'] = home["home_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/3475939722.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home["goals"] = home["away_goals"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/3475939722.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["club"] = away["away_team"]
/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_33123/3475939722.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  away["goals"] = away["home_goals"]

                          goals
club
AFC Bournemouth            61.0
Arsenal                    51.0
Brighton and Hove Albion   54.0
Burnley                    39.0
Chelsea                    38.0
Crystal Palace             55.0
Everton                    58.0
Huddersfield Town          58.0
Leicester City             60.0
Liverpool                  38.0
Manchester City            27.0
Manchester United          28.0
Newcastle United           47.0
Southampton                56.0
Stoke City                 68.0
Swansea City               56.0
Tottenham Hotspur          36.0
Watford                    64.0
West Bromwich Albion       56.0
West Ham United            68.0

In [111]:
league_table = league_table.merge(against_goals, on="club", how="inner")

In [121]:
league_table.rename(columns={"goals":"GA"}, inplace=True)
league_table = league_table.sort_values(by="PTS", ascending=False)

league_table["GD"] = league_table["GF"] - league_table["GA"]
remove_col = league_table.columns.tolist()

remove_col.remove("PTS")
remove_col.append("PTS")

league_table = league_table[remove_col]

league_table

                           P   D   L   W     GF    GA    GD  PTS
club
Manchester City           38   4   2  32  106.0  27.0  79.0  100
Manchester United         38   6   7  25   68.0  28.0  40.0   81
Tottenham Hotspur         38   8   7  23   74.0  36.0  38.0   77
Liverpool                 38  12   5  21   84.0  38.0  46.0   75
Chelsea                   38   7  10  21   62.0  38.0  24.0   70
Arsenal                   38   6  13  19   74.0  51.0  23.0   63
Burnley                   38  12  12  14   36.0  39.0  -3.0   54
Everton                   38  10  15  13   44.0  58.0 -14.0   49
Leicester City            38  11  15  12   56.0  60.0  -4.0   47
Crystal Palace            38  11  16  11   45.0  55.0 -10.0   44
AFC Bournemouth           38  11  16  11   45.0  61.0 -16.0   44
Newcastle United          38   8  18  12   39.0  47.0  -8.0   44
West Ham United           38  12  16  10   48.0  68.0 -20.0   42
Watford                   38   8  19  11   44.0  64.0 -20.0   41
Brighton and Hove Albion  38  13  16   9   34.0  54.0 -20.0   40
Huddersfield Town         38  10  19   9   28.0  58.0 -30.0   37
Southampton               38  15  16   7   37.0  56.0 -19.0   36
Stoke City                38  12  19   7   35.0  68.0 -33.0   33
Swansea City              38   9  21   8   28.0  56.0 -28.0   33
West Bromwich Albion      38  13  19   6   31.0  56.0 -25.0   31

In [123]:
premier_league_result["season"]

4180    2017-2018
4181    2017-2018
4182    2017-2018
4183    2017-2018
4184    2017-2018
          ...
4555    2017-2018
4556    2017-2018
4557    2017-2018
4558    2017-2018
4559    2017-2018
Name: season, Length: 380, dtype: object

In [143]:
premier_league_result

,home_team,away_team,home_goals,away_goals,result,season
4180,Arsenal,Leicester City,4.0,3.0,H,2017-2018
4181,Watford,Liverpool,3.0,3.0,D,2017-2018
4182,Chelsea,Burnley,2.0,3.0,A,2017-2018
4183,Crystal Palace,Huddersfield Town,0.0,3.0,A,2017-2018
4184,Everton,Stoke City,1.0,0.0,H,2017-2018
...,...,...,...,...,...,...
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018
4559,West Ham United,Everton,3.0,1.0,H,2017-2018

In [145]:
premier_league_stat.head(40)

,team,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,...,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches,season
0,Manchester United,28.0,5.0,83.0,60.0,1.0,698.0,256.0,21.0,12.0,...,918.0,258.0,25686.0,NaN,1.0,NaN,2.0,37.0,25.0,2006-2007
1,Chelsea,24.0,3.0,64.0,62.0,4.0,636.0,216.0,14.0,16.0,...,897.0,231.0,24010.0,NaN,2.0,NaN,1.0,74.0,22.0,2006-2007
2,Liverpool,20.0,10.0,57.0,44.0,0.0,668.0,214.0,15.0,8.0,...,1107.0,282.0,24150.0,NaN,1.0,NaN,0.0,51.0,27.0,2006-2007
3,Arsenal,19.0,8.0,63.0,59.0,3.0,638.0,226.0,19.0,10.0,...,873.0,278.0,25592.0,NaN,1.0,NaN,0.0,88.0,27.0,2006-2007
4,Tottenham Hotspur,17.0,12.0,57.0,48.0,3.0,520.0,184.0,6.0,5.0,...,796.0,181.0,22200.0,NaN,2.0,NaN,0.0,51.0,24.0,2006-2007
5,Bolton Wanderers,16.0,14.0,47.0,84.0,4.0,404.0,120.0,7.0,10.0,...,942.0,217.0,18932.0,NaN,6.0,NaN,2.0,44.0,21.0,2006-2007
6,Reading,16.0,15.0,52.0,38.0,3.0,419.0,132.0,8.0,15.0,...,1067.0,280.0,18017.0,NaN,2.0,NaN,0.0,63.0,21.0,2006-2007
7,Blackburn Rovers,15.0,16.0,52.0,77.0,6.0,478.0,155.0,5.0,12.0,...,911.0,205.0,20812.0,NaN,8.0,NaN,5.0,56.0,25.0,2006-2007
8,Everton,15.0,10.0,52.0,65.0,2.0,465.0,153.0,9.0,9.0,...,867.0,208.0,19250.0,NaN,2.0,NaN,1.0,83.0,15.0,2006-2007
9,Portsmouth,14.0,12.0,45.0,48.0,1.0,525.0,186.0,9.0,13.0,...,783.0,247.0,19377.0,NaN,4.0,NaN,2.0,79.0,30.0,2006-2007
10,Middlesbrough,12.0,16.0,44.0,64.0,2.0,454.0,144.0,7.0,7.0,...,769.0,187.0,19199.0,NaN,5.0,NaN,0.0,78.0,37.0,2006-2007
11,West Ham United,12.0,21.0,35.0,85.0,2.0,461.0,134.0,8.0,3.0,...,849.0,196.0,20040.0,NaN,5.0,NaN,0.0,64.0,25.0,2006-2007
12,Aston Villa,11.0,10.0,43.0,48.0,1.0,470.0,154.0,9.0,5.0,...,886.0,213.0,20002.0,NaN,5.0,NaN,0.0,57.0,26.0,2006-2007
13,Manchester City,11.0,18.0,29.0,59.0,4.0,454.0,147.0,5.0,3.0,...,811.0,198.0,19378.0,NaN,4.0,NaN,1.0,64.0,17.0,2006-2007
14,Newcastle United,11.0,17.0,38.0,65.0,1.0,454.0,140.0,11.0,8.0,...,793.0,195.0,21213.0,NaN,9.0,NaN,0.0,48.0,26.0,2006-2007
15,Sheffield United,10.0,20.0,32.0,68.0,2.0,483.0,147.0,14.0,10.0,...,800.0,178.0,17713.0,NaN,8.0,NaN,1.0,43.0,21.0,2006-2007
16,Wigan Athletic,10.0,20.0,37.0,73.0,3.0,474.0,147.0,9.0,6.0,...,813.0,177.0,17564.0,NaN,4.0,NaN,2.0,61.0,29.0,2006-2007
17,Charlton Athletic,8.0,20.0,34.0,56.0,4.0,418.0,133.0,11.0,6.0,...,750.0,178.0,19497.0,NaN,7.0,NaN,2.0,50.0,13.0,2006-2007
18,Fulham,8.0,15.0,38.0,56.0,3.0,451.0,142.0,8.0,8.0,...,895.0,173.0,18720.0,NaN,6.0,NaN,1.0,45.0,22.0,2006-2007
19,Watford,5.0,20.0,29.0,45.0,2.0,418.0,135.0,10.0,4.0,...,983.0,212.0,16772.0,NaN,3.0,NaN,0.0,63.0,15.0,2006-2007
20,Manchester United,27.0,5.0,80.0,51.0,2.0,696.0,260.0,16.0,12.0,...,936.0,261.0,26620.0,NaN,10.0,627.0,0.0,47.0,23.0,2007-2008
21,Chelsea,25.0,3.0,65.0,63.0,5.0,605.0,199.0,12.0,10.0,...,945.0,253.0,26290.0,NaN,8.0,687.0,0.0,62.0,19.0,2007-2008
22,Arsenal,24.0,3.0,74.0,55.0,3.0,627.0,208.0,13.0,14.0,...,888.0,234.0,28156.0,NaN,2.0,776.0,1.0,45.0,26.0,2007-2008
23,Liverpool,21.0,4.0,67.0,45.0,1.0,686.0,214.0,13.0,7.0,...,932.0,237.0,25857.0,NaN,4.0,613.0,1.0,42.0,22.0,2007-2008
24,Everton,19.0,11.0,55.0,40.0,3.0,474.0,169.0,4.0,13.0,...,877.0,198.0,21360.0,NaN,8.0,620.0,0.0,55.0,20.0,2007-2008
25,Aston Villa,16.0,10.0,71.0,54.0,4.0,511.0,182.0,11.0,16.0,...,932.0,229.0,20734.0,NaN,6.0,655.0,2.0,40.0,14.0,2007-2008
26,Portsmouth,16.0,13.0,48.0,55.0,3.0,559.0,160.0,9.0,4.0,...,663.0,184.0,21907.0,NaN,4.0,683.0,2.0,77.0,28.0,2007-2008
27,Blackburn Rovers,15.0,10.0,50.0,72.0,6.0,530.0,185.0,14.0,11.0,...,883.0,196.0,22599.0,NaN,5.0,532.0,2.0,59.0,27.0,2007-2008
28,Manchester City,15.0,13.0,45.0,50.0,4.0,423.0,143.0,5.0,5.0,...,695.0,156.0,23416.0,NaN,7.0,559.0,2.0,45.0,43.0,2007-2008
29,West Ham United,13.0,15.0,42.0,63.0,1.0,500.0,154.0,15.0,7.0,...,910.0,207.0,22347.0,NaN,8.0,511.0,3.0,77.0,19.0,2007-2008
30,Newcastle United,11.0,17.0,45.0,63.0,1.0,481.0,153.0,10.0,10.0,...,966.0,209.0,22761.0,NaN,8.0,717.0,0.0,35.0,20.0,2007-2008
31,Sunderland,11.0,21.0,36.0,65.0,4.0,483.0,137.0,7.0,10.0,...,889.0,183.0,21415.0,NaN,5.0,586.0,0.0,40.0,25.0,2007-2008
32,Tottenham Hotspur,11.0,14.0,66.0,51.0,1.0,555.0,195.0,19.0,12.0,...,994.0,238.0,24679.0,NaN,6.0,612.0,0.0,46.0,21.0,2007-2008
33,Middlesbrough,10.0,16.0,43.0,86.0,2.0,499.0,152.0,13.0,9.0,...,960.0,219.0,21064.0,NaN,2.0,575.0,0.0,68.0,38.0,2007-2008
34,Reading,10.0,22.0,41.0,59.0,5.0,441.0,132.0,10.0,12.0,...,1087.0,238.0,19140.0,NaN,6.0,532.0,2.0,61.0,28.0,2007-2008
35,Wigan Athletic,10.0,18.0,34.0,59.0,4.0,489.0,141.0,11.0,6.0,...,767.0,186.0,19855.0,NaN,7.0,510.0,1.0,68.0,14.0,2007-2008
36,Bolton Wanderers,9.0,19.0,36.0,76.0,0.0,451.0,149.0,14.0,5.0,...,905.0,208.0,20846.0,NaN,6.0,545.0,0.0,47.0,20.0,2007-2008
37,Birmingham City,8.0,19.0,46.0,70.0,3.0,414.0,143.0,6.0,6.0,...,774.0,193.0,19541.0,NaN,6.0,551.0,0.0,77.0,11.0,2007-2008
38,Fulham,8.0,18.0,38.0,55.0,6.0,469.0,154.0,7.0,7.0,...,849.0,183.0,21259.0,NaN,4.0,589.0,0.0,55.0,27.0,2007-2008
39,Derby County,1.0,29.0,20.0,63.0,1.0,376.0,116.0,7.0,3.0,...,804.0,158.0,20140.0,NaN,5.0,464.0,0.0,68.0,24.0,2007-2008

In [7]:
laliga = pd.read_csv("./Laliga_results_csv")
laliga.sample(60)

,home_team,away_team,home_team_goal,away_team_goal,result,season
2544,Getafe CF,Levante UD,0,1,A,2014/2015
2673,Real Madrid CF,UD Las Palmas,3,1,H,2015/2016
1598,Granada CF,Real Sociedad,0,0,D,2012/2013
1373,Real Madrid CF,Real Sociedad,5,1,H,2011/2012
1545,Athletic Club de Bilbao,Sevilla FC,2,1,H,2012/2013
227,UD Almería,Málaga CF,1,0,H,2008/2009
2917,RCD Espanyol,Atlético Madrid,1,3,A,2015/2016
1979,CA Osasuna,Real Madrid CF,2,2,D,2013/2014
693,UD Almería,Sevilla FC,2,3,A,2009/2010
1023,Valencia CF,Real Madrid CF,3,6,A,2010/2011
2703,Sevilla FC,Valencia CF,1,0,H,2015/2016
1552,Valencia CF,RCD Espanyol,2,1,H,2012/2013
464,Villarreal CF,UD Almería,1,1,D,2009/2010
1447,RCD Mallorca,Levante UD,1,0,H,2011/2012
229,Atlético Madrid,RC Recreativo,4,0,H,2008/2009
2738,Athletic Club de Bilbao,Levante UD,2,0,H,2015/2016
2388,Valencia CF,UD Almería,3,2,H,2014/2015
1115,Racing Santander,UD Almería,1,0,H,2010/2011
1627,Atlético Madrid,Real Zaragoza,2,0,H,2012/2013
177,Racing Santander,CA Osasuna,1,1,D,2008/2009
3010,Sevilla FC,FC Barcelona,2,1,H,2015/2016
2519,SD Eibar,Málaga CF,1,0,H,2014/2015
2670,SD Eibar,Rayo Vallecano,1,0,H,2015/2016
1456,Racing Santander,CA Osasuna,2,4,A,2011/2012
2076,Real Valladolid,Levante UD,1,1,D,2013/2014
2918,Granada CF,Málaga CF,0,0,D,2015/2016
1570,CA Osasuna,Rayo Vallecano,1,0,H,2012/2013
1604,RCD Espanyol,RC Deportivo de La Coruña,2,0,H,2012/2013
2783,FC Barcelona,Athletic Club de Bilbao,6,0,H,2015/2016
1301,Real Madrid CF,Racing Santander,4,0,H,2011/2012
808,Racing Santander,RC Deportivo de La Coruña,1,0,H,2010/2011
1204,FC Barcelona,Levante UD,5,0,H,2011/2012
2879,Granada CF,RCD Espanyol,1,1,D,2015/2016
181,CA Osasuna,Real Sporting de Gijón,1,2,A,2008/2009
265,Málaga CF,RC Deportivo de La Coruña,1,1,D,2008/2009
3003,Getafe CF,Levante UD,3,0,H,2015/2016
1633,RCD Espanyol,Real Zaragoza,1,2,A,2012/2013
172,Athletic Club de Bilbao,Sevilla FC,1,2,A,2008/2009
647,Real Madrid CF,Valencia CF,2,0,H,2009/2010
47,Málaga CF,CA Osasuna,4,2,H,2008/2009
2041,Granada CF,RC Celta de Vigo,1,2,A,2013/2014
1157,Real Zaragoza,Valencia CF,0,1,A,2011/2012
1245,Atlético Madrid,Villarreal CF,3,0,H,2011/2012
858,Racing Santander,Real Sporting de Gijón,1,1,D,2010/2011
2391,RCD Espanyol,Sevilla FC,1,2,A,2014/2015
1306,Real Sporting de Gijón,Atlético Madrid,1,1,D,2011/2012
2377,Real Madrid CF,RCD Espanyol,3,0,H,2014/2015
959,Levante UD,RCD Espanyol,1,0,H,2010/2011
715,CA Osasuna,Real Sporting de Gijón,1,0,H,2009/2010
1277,Real Sociedad,Real Sporting de Gijón,5,1,H,2011/2012
3028,Real Sporting de Gijón,Granada CF,3,3,D,2015/2016
109,Villarreal CF,RCD Mallorca,2,0,H,2008/2009
209,Real Madrid CF,UD Almería,3,0,H,2008/2009
610,Sevilla FC,CD Tenerife,3,0,H,2009/2010
2320,Atlético Madrid,RC Deportivo de La Coruña,2,0,H,2014/2015
140,RCD Mallorca,RC Deportivo de La Coruña,1,1,D,2008/2009
2593,Granada CF,Atlético Madrid,0,0,D,2014/2015
2615,Real Madrid CF,Elche CF,5,1,H,2014/2015
2451,RCD Espanyol,Córdoba CF,1,0,H,2014/2015
1053,Real Sociedad,Real Zaragoza,2,1,H,2010/2011

In [11]:
laliga.loc[laliga["season"].str.contains("2009/2010")][["home_team", "away_team"]].sample(50)

                     home_team                  away_team
556                 CA Osasuna                  Getafe CF
742                 Sevilla FC               RCD Espanyol
398                 UD Almería                 CA Osasuna
532             Real Madrid CF              Villarreal CF
427    Athletic Club de Bilbao                Valencia CF
383                 CA Osasuna              Villarreal CF
594  RC Deportivo de La Coruña                  Getafe CF
430            Real Valladolid                  Málaga CF
712             Real Madrid CF                CD Tenerife
591              Villarreal CF                 Sevilla FC
461            Real Valladolid            Atlético Madrid
658                 CA Osasuna    Athletic Club de Bilbao
405             Real Madrid CF           Racing Santander
694                Valencia CF                CD Tenerife
705            Real Valladolid                 CA Osasuna
506            Real Valladolid                 UD Almería
595             Real Madrid CF            Atlético Madrid
520               RCD Espanyol  RC Deportivo de La Coruña
489             Real Madrid CF                  Málaga CF
459               RCD Mallorca    Athletic Club de Bilbao
564     Real Sporting de Gijón    Athletic Club de Bilbao
641                 Sevilla FC     Real Sporting de Gijón
627    Athletic Club de Bilbao                 UD Almería
440            Real Valladolid     Real Sporting de Gijón
421                CD Tenerife     Real Sporting de Gijón
425  RC Deportivo de La Coruña               FC Barcelona
597               RCD Mallorca               FC Barcelona
431     Real Sporting de Gijón                 Sevilla FC
654               FC Barcelona       Xerez Club Deportivo
540       Xerez Club Deportivo               RCD Espanyol
511             Real Madrid CF               RCD Espanyol
730       Xerez Club Deportivo              Villarreal CF
648    Athletic Club de Bilbao              Real Zaragoza
471            Atlético Madrid     Real Sporting de Gijón
634           Racing Santander               RCD Espanyol
678               RCD Mallorca             Real Madrid CF
741                CD Tenerife       Xerez Club Deportivo
700               RCD Espanyol                  Málaga CF
490  RC Deportivo de La Coruña                  Málaga CF
689             Real Madrid CF    Athletic Club de Bilbao
412     Real Sporting de Gijón              Villarreal CF
528            Atlético Madrid               FC Barcelona
751       Xerez Club Deportivo                 Sevilla FC
422              Villarreal CF                  Getafe CF
384              Real Zaragoza                CD Tenerife
443              Villarreal CF           Racing Santander
665       Xerez Club Deportivo                 UD Almería
708            Atlético Madrid                 UD Almería
460     Real Sporting de Gijón                  Getafe CF
414            Atlético Madrid               RCD Espanyol