In [3]:
import sqlite3
import pandas as pd
import numpy as np


database_connection = sqlite3.connect("database.sqlite")

match_dataframe = pd.read_sql_query("SELECT * FROM Match", database_connection)
player_dataframe = pd.read_sql_query("SELECT * FROM Player", database_connection)
player_attributes_dataframe = pd.read_sql_query("SELECT * FROM Player_Attributes", database_connection)
league_dataframe = pd.read_sql_query("SELECT * FROM League", database_connection)
country_dataframe = pd.read_sql_query("SELECT * FROM Country", database_connection)
team_dataframe = pd.read_sql_query("SELECT * FROM Team", database_connection)
team_attributes_dataframe = pd.read_sql_query("SELECT * FROM Team_Attributes", database_connection)
sqlite_sequence = pd.read_sql_query("SELECT * FROM sqlite_sequence", database_connection)


player_attributes_dataframe.sort_values(by="overall_rating", ascending=False)
player_data = player_dataframe.merge(player_attributes_dataframe, on="player_api_id", how="left")
player_data.sort_values(by="overall_rating", ascending=False)[["player_name", "overall_rating", "free_kick_accuracy"]].head(50)
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", database_connection)
print(tables)

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

In [28]:
player_data.loc[player_data["player_name"] == "Karim Benzema"]

,id_x,player_api_id,player_name,player_fifa_api_id_x,birthday,height,weight,id_y,player_fifa_api_id_y,date,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
93533,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93534,165153,2015-12-24 00:00:00,...,83.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93534,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93535,165153,2015-11-06 00:00:00,...,83.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93535,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93536,165153,2015-10-16 00:00:00,...,83.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93536,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93537,165153,2015-09-21 00:00:00,...,83.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93537,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93538,165153,2015-04-24 00:00:00,...,81.0,82.0,25.0,25.0,25.0,13.0,11.0,5.0,5.0,7.0
93538,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93539,165153,2014-10-31 00:00:00,...,81.0,82.0,25.0,25.0,25.0,13.0,11.0,5.0,5.0,7.0
93539,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93540,165153,2014-09-18 00:00:00,...,81.0,82.0,25.0,25.0,25.0,13.0,11.0,5.0,5.0,7.0
93540,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93541,165153,2014-07-18 00:00:00,...,81.0,82.0,25.0,25.0,25.0,13.0,11.0,5.0,5.0,7.0
93541,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93542,165153,2013-09-20 00:00:00,...,81.0,82.0,25.0,25.0,25.0,13.0,11.0,5.0,5.0,7.0
93542,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93543,165153,2013-03-15 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93543,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93544,165153,2013-03-01 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93544,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93545,165153,2013-02-15 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93545,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93546,165153,2012-08-31 00:00:00,...,81.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93546,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93547,165153,2012-02-22 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93547,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93548,165153,2011-08-30 00:00:00,...,76.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93548,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93549,165153,2011-02-22 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93549,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93550,165153,2010-08-30 00:00:00,...,78.0,82.0,13.0,15.0,12.0,13.0,11.0,5.0,5.0,7.0
93550,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93551,165153,2010-02-22 00:00:00,...,78.0,80.0,23.0,25.0,12.0,2.0,21.0,47.0,21.0,21.0
93551,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93552,165153,2009-08-30 00:00:00,...,78.0,80.0,32.0,38.0,12.0,2.0,21.0,47.0,21.0,21.0
93552,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93553,165153,2008-08-30 00:00:00,...,78.0,80.0,40.0,45.0,12.0,2.0,21.0,47.0,21.0,21.0
93553,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93554,165153,2007-08-30 00:00:00,...,78.0,71.0,21.0,35.0,12.0,2.0,21.0,47.0,21.0,21.0
93554,5636,26166,Karim Benzema,165153,1987-12-19 00:00:00,187.96,174,93555,165153,2007-02-22 00:00:00,...,78.0,71.0,18.0,35.0,12.0,2.0,6.0,47.0,6.0,7.0

In [29]:
player_dataframe

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [30]:
player_dataframe.loc[player_dataframe["player_name"] == "Lionel Messi"]

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
6169,6176,30981,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159

In [48]:
player_data.columns.unique()

Index(['id_x', 'player_api_id', 'player_name', 'player_fifa_api_id_x',
       'birthday', 'height', 'weight', 'id_y', 'player_fifa_api_id_y', 'date',
       'overall_rating', 'potential', 'preferred_foot', 'attacking_work_rate',
       'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes'],
      dtype='object')

In [16]:
player_data.columns.unique()

league_dataframe

country_dataframe

country_league = pd.merge(country_dataframe, league_dataframe, on="id", how="inner")
country_league

       id       name_x  country_id                    name_y
0       1      Belgium           1    Belgium Jupiler League
1    1729      England        1729    England Premier League
2    4769       France        4769            France Ligue 1
3    7809      Germany        7809     Germany 1. Bundesliga
4   10257        Italy       10257             Italy Serie A
5   13274  Netherlands       13274    Netherlands Eredivisie
6   15722       Poland       15722        Poland Ekstraklasa
7   17642     Portugal       17642  Portugal Liga ZON Sagres
8   19694     Scotland       19694   Scotland Premier League
9   21518        Spain       21518           Spain LIGA BBVA
10  24558  Switzerland       24558  Switzerland Super League

In [42]:
team_attributes_dataframe

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,1454,15005,10000,2011-02-22 00:00:00,52,Balanced,NaN,Little,52,Mixed,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,1455,15005,10000,2012-02-22 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,1456,15005,10000,2013-09-20 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,1457,15005,10000,2014-09-19 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,1458,15005,10000,2015-09-10 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

In [ ]:
player_data.sort_values(by="overall_rating", ascending=False)[["player_name", "overall_rating", "preferred_foot", ""]].sample(30)

                  player_name  overall_rating
174538            Tony Taylor            61.0
87202              Jordi Alba            81.0
120735       Maurizio Lanzaro            71.0
87220              Jordi Amat            74.0
81223       Jerome Roussillon            72.0
169555           Theo Walcott            81.0
65303            Glenn Murray            64.0
39315       David Ducourtioux            70.0
53091          Fabien Lemoine            72.0
54669        Federico Viviani            69.0
9343             Alvaro Anton            66.0
22111             Bojan Krkic            79.0
21455   Billy Ketkeophomphone            63.0
112558        Marcos Angeleri            72.0
180955         Yacine Brahimi            78.0
63703       Gianluca Frontino            60.0
39175             David Davis            65.0
142982         Petter Hansson            75.0
35223           Daniel Davari            65.0
128186       Mohammed Bangura            69.0
70345           Hernan Losada            70.0
50673            Enzo Maresca            68.0
109529             Marc Janko            70.0
18852           Baptiste Aloe            61.0
181937         Yoel Rodriguez            72.0
90191     Juan Carlos Paredes            68.0
3084            Adrian Stoian            69.0
35417        Daniel Galbraith            59.0
80218              Jens Janse            62.0
613              Abdoulaye Ba            73.0

In [10]:
player_data.columns.unique()
team_attributes_dataframe.columns. unique()

Index(['id', 'team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')

In [8]:
player_data.sort_values(by="potential", ascending=False)[["player_name", "overall_rating", "potential"]].head(40)

               player_name  overall_rating  potential
102492        Lionel Messi            94.0       97.0
102491        Lionel Messi            94.0       97.0
102496        Lionel Messi            94.0       97.0
102495        Lionel Messi            94.0       97.0
102494        Lionel Messi            94.0       97.0
102493        Lionel Messi            94.0       97.0
102497        Lionel Messi            94.0       96.0
102499        Lionel Messi            94.0       96.0
102498        Lionel Messi            94.0       96.0
33339    Cristiano Ronaldo            92.0       95.0
102503        Lionel Messi            90.0       95.0
102501        Lionel Messi            90.0       95.0
33340    Cristiano Ronaldo            92.0       95.0
102504        Lionel Messi            90.0       95.0
33341    Cristiano Ronaldo            92.0       95.0
102505        Lionel Messi            90.0       95.0
153453          Ronaldinho            91.0       95.0
33338    Cristiano Ronaldo            92.0       95.0
102484        Lionel Messi            94.0       95.0
102486        Lionel Messi            93.0       95.0
102487        Lionel Messi            93.0       95.0
102488        Lionel Messi            93.0       95.0
102489        Lionel Messi            93.0       95.0
102490        Lionel Messi            93.0       95.0
33342    Cristiano Ronaldo            92.0       94.0
33348    Cristiano Ronaldo            89.0       94.0
183689  Zlatan Ibrahimovic            89.0       94.0
33350    Cristiano Ronaldo            89.0       94.0
33343    Cristiano Ronaldo            92.0       94.0
33346    Cristiano Ronaldo            92.0       94.0
33344    Cristiano Ronaldo            92.0       94.0
33351    Cristiano Ronaldo            90.0       94.0
33352    Cristiano Ronaldo            91.0       94.0
151534             Robinho            86.0       94.0
131467              Neymar            89.0       94.0
183688  Zlatan Ibrahimovic            89.0       94.0
33345    Cristiano Ronaldo            92.0       94.0
102507        Lionel Messi            85.0       94.0
102502        Lionel Messi            90.0       94.0
102500        Lionel Messi            90.0       94.0

In [19]:
match_dataframe.columns.unique().tolist()

['id',
 'country_id',
 'league_id',
 'season',
 'stage',
 'date',
 'match_api_id',
 'home_team_api_id',
 'away_team_api_id',
 'home_team_goal',
 'away_team_goal',
 'home_player_X1',
 'home_player_X2',
 'home_player_X3',
 'home_player_X4',
 'home_player_X5',
 'home_player_X6',
 'home_player_X7',
 'home_player_X8',
 'home_player_X9',
 'home_player_X10',
 'home_player_X11',
 'away_player_X1',
 'away_player_X2',
 'away_player_X3',
 'away_player_X4',
 'away_player_X5',
 'away_player_X6',
 'away_player_X7',
 'away_player_X8',
 'away_player_X9',
 'away_player_X10',
 'away_player_X11',
 'home_player_Y1',
 'home_player_Y2',
 'home_player_Y3',
 'home_player_Y4',
 'home_player_Y5',
 'home_player_Y6',
 'home_player_Y7',
 'home_player_Y8',
 'home_player_Y9',
 'home_player_Y10',
 'home_player_Y11',
 'away_player_Y1',
 'away_player_Y2',
 'away_player_Y3',
 'away_player_Y4',
 'away_player_Y5',
 'away_player_Y6',
 'away_player_Y7',
 'away_player_Y8',
 'away_player_Y9',
 'away_player_Y10',
 'away_player_Y11',
 'home_player_1',
 'home_player_2',
 'home_player_3',
 'home_player_4',
 'home_player_5',
 'home_player_6',
 'home_player_7',
 'home_player_8',
 'home_player_9',
 'home_player_10',
 'home_player_11',
 'away_player_1',
 'away_player_2',
 'away_player_3',
 'away_player_4',
 'away_player_5',
 'away_player_6',
 'away_player_7',
 'away_player_8',
 'away_player_9',
 'away_player_10',
 'away_player_11',
 'goal',
 'shoton',
 'shotoff',
 'foulcommit',
 'card',
 'cross',
 'corner',
 'possession',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'SJH',
 'SJD',
 'SJA',
 'VCH',
 'VCD',
 'VCA',
 'GBH',
 'GBD',
 'GBA',
 'BSH',
 'BSD',
 'BSA']

In [20]:
league_dataframe

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [53]:
team_dataframe.loc[team_dataframe["team_long_name"] == "Real Madrid CF"]

        id  team_api_id  team_fifa_api_id  team_long_name team_short_name
256  43040         8633             243.0  Real Madrid CF             REA

In [62]:
team_attributes_dataframe

each_team = pd.merge(team_dataframe, team_attributes_dataframe, on="team_fifa_api_id", how="outer")
each_team.rename(columns={"team_fifa_api_id_y": "team_fifa_api_id"}, inplace=True)


each_team.columns.unique()

Index(['id_x', 'team_api_id_x', 'team_fifa_api_id', 'team_long_name',
       'team_short_name', 'id_y', 'team_api_id_y', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='object')

In [59]:
league_dataframe
country_league

       id       name_x  country_id                    name_y
0       1      Belgium           1    Belgium Jupiler League
1    1729      England        1729    England Premier League
2    4769       France        4769            France Ligue 1
3    7809      Germany        7809     Germany 1. Bundesliga
4   10257        Italy       10257             Italy Serie A
5   13274  Netherlands       13274    Netherlands Eredivisie
6   15722       Poland       15722        Poland Ekstraklasa
7   17642     Portugal       17642  Portugal Liga ZON Sagres
8   19694     Scotland       19694   Scotland Premier League
9   21518        Spain       21518           Spain LIGA BBVA
10  24558  Switzerland       24558  Switzerland Super League

In [86]:
each_team

each_team_data = each_team[["team_api_id_x", "team_long_name", "team_short_name"]]

In [67]:
league_dataframe.columns.unique()

Index(['id', 'country_id', 'name'], dtype='object')

In [168]:
country_dataframe.columns.unique()

country_league
match_dataframe

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
matches_in_league = pd.merge(match_dataframe, country_league, on="country_id", how="inner")
matches_in_league

# matches_in_league.loc[matches_in_league["name_x"] == "England"]
# matches_in_league.rename(columns={"home_team_api_id":"team_api_id_x"}, inplace=True)
# each_team
# home_team_league = pd.merge(matches_in_league, each_team_data, on="team_api_id_x", how="inner")
# premier_league = home_team_league.loc[home_team_league["name_x"] == "England"]
# premier_league.drop(columns=["team_api_id_x"], inplace=True)
# premier_league.rename(columns={"away_team_api_id"})

,id_x,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,VCA,GBH,GBD,GBA,BSH,BSD,BSA,id_y,name_x,name_y
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.50,1.78,3.25,4.00,1.73,3.40,4.20,1,Belgium,Belgium Jupiler League
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.25,1.85,3.25,3.75,1.91,3.25,3.60,1,Belgium,Belgium Jupiler League
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.65,2.50,3.20,2.50,2.30,3.20,2.75,1,Belgium,Belgium Jupiler League
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,6.50,1.50,3.75,5.50,1.44,3.75,6.50,1,Belgium,Belgium Jupiler League
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.65,4.50,3.50,1.65,4.75,3.30,1.67,1,Belgium,Belgium Jupiler League
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,Switzerland Super League
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,Switzerland Super League
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,Switzerland Super League
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,Switzerland Super League
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24558,Switzerland,Switzerland Super League

In [150]:
premier_league.rename(columns={"away_team_api_id":"team_api_id_x", "team_long_name": "home_team"}, inplace=True)
premier_league

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_69975/2834182360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  premier_league.rename(columns={"away_team_api_id":"team_api_id_x", "team_long_name": "home_team"}, inplace=True)

,id_x,country_id,league_id,season,stage,date,match_api_id,team_api_id_x,home_team_goal,away_team_goal,...,GBD,GBA,BSH,BSD,BSA,id_y,name_x,name_y,home_team,team_short_name
8610,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,4.75,10.0,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN
8611,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,4.75,10.0,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN
8612,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,4.75,10.0,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN
8613,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,4.75,10.0,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN
8614,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,4.75,10.0,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26845,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA
26846,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA
26847,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA
26848,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA
26849,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA

In [151]:
away_team = pd.merge(premier_league, each_team_data, on="team_api_id_x", how="inner")
premier_league = away_team
premier_league

,id_x,country_id,league_id,season,stage,date,match_api_id,team_api_id_x,home_team_goal,away_team_goal,...,BSH,BSD,BSA,id_y,name_x,name_y,home_team,team_short_name_x,team_long_name,team_short_name_y
0,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
1,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
2,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
3,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
4,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109435,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA,Sunderland,SUN
109436,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA,Sunderland,SUN
109437,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA,Sunderland,SUN
109438,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA,Sunderland,SUN
109439,4768,1729,1729,2015/2016,9,2015-10-17 00:00:00,1988799,8472,1,0,...,NaN,NaN,NaN,1729,England,England Premier League,West Bromwich Albion,WBA,Sunderland,SUN

In [152]:
premier_league.rename(columns={"team_short_name_x":"home_team_short", "team_long_name": "away_team", "team_short_name_y": "away_team_short"}, inplace=True)
premier_league
premier_league.head(60)

,id_x,country_id,league_id,season,stage,date,match_api_id,team_api_id_x,home_team_goal,away_team_goal,...,BSH,BSD,BSA,id_y,name_x,name_y,home_team,home_team_short,away_team,away_team_short
0,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
1,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
2,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
3,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
4,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
5,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
6,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
7,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
8,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
9,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
10,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
11,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
12,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
13,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
14,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
15,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
16,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
17,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
18,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
19,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
20,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
21,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
22,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
23,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
24,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
25,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
26,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
27,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
28,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
29,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
30,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
31,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
32,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
33,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
34,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
35,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10261,1,1,...,1.29,4.5,11.0,1729,England,England Premier League,Manchester United,MUN,Newcastle United,NEW
36,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
37,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
38,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
39,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
40,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
41,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
42,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
43,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
44,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
45,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
46,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
47,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
48,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
49,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
50,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
51,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
52,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
53,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
54,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
55,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
56,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
57,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
58,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA
59,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,8659,1,0,...,1.22,5.0,13.0,1729,England,England Premier League,Arsenal,ARS,West Bromwich Albion,WBA

In [154]:
premier_league["result"] = np.where(premier_league["home_team_goal"] == premier_league["away_team_goal"], "D", 
                                          (np.where(premier_league["home_team_goal"] > premier_league["away_team_goal"], "H", 
                                                    "A")))


premier_league = premier_league[["home_team", "away_team", "home_team_goal", "away_team_goal", "result", "season"]]

In [ ]:
premier_league = premier_league.drop_duplicates()
premier_league.rename(columns={"home_team_goal": "home_goals", "away_team_goal":"away_goals"}, inplace=True)
premier_league

,home_team,away_team,home_goals,away_goals,result,season
0,Manchester United,Newcastle United,1,1,D,2008/2009
36,Arsenal,West Bromwich Albion,1,0,H,2008/2009
72,Sunderland,Liverpool,0,1,A,2008/2009
108,West Ham United,Wigan Athletic,2,1,H,2008/2009
144,Aston Villa,Manchester City,4,2,H,2008/2009
...,...,...,...,...,...,...
109260,Southampton,Leicester City,2,2,D,2015/2016
109296,Swansea City,Stoke City,0,1,A,2015/2016
109332,Tottenham Hotspur,Liverpool,0,0,D,2015/2016
109368,Watford,Arsenal,0,3,A,2015/2016
109404,West Bromwich Albion,Sunderland,1,0,H,2015/2016

In [164]:
premier_league.to_csv("premier_league_results_csv", index=False)

In [169]:
country_league

       id       name_x  country_id                    name_y
0       1      Belgium           1    Belgium Jupiler League
1    1729      England        1729    England Premier League
2    4769       France        4769            France Ligue 1
3    7809      Germany        7809     Germany 1. Bundesliga
4   10257        Italy       10257             Italy Serie A
5   13274  Netherlands       13274    Netherlands Eredivisie
6   15722       Poland       15722        Poland Ekstraklasa
7   17642     Portugal       17642  Portugal Liga ZON Sagres
8   19694     Scotland       19694   Scotland Premier League
9   21518        Spain       21518           Spain LIGA BBVA
10  24558  Switzerland       24558  Switzerland Super League

In [172]:
league_name = country_league.loc[country_league["name_x"] == "Germany"]["name_y"].to_string()

In [262]:
match_dataframe["goal"].sample(50)

12159                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>15</elapsed><player1>150330</player1><sortorder>0</sortorder><team>9875</team><id>3110693</id><n>17</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>20</elapsed><player1>41658</player1><sortorder>0</sortorder><team>9875</team><id>3110701</id><n>16</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>25</elapsed><player1>166509</player1><sortorder>0</sortorder><team>8530</team><id>3110709</id><n>15</n><type>goal</type><goal_type>n</goal_type></value></goal>
3793                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>80</event_incident_typefk><elapsed>32</elapsed><subtype>shot</subtype><player1>31306</player1><sortorder>2</sortorder><team>8455</team><id>3243655</id><n>300</n><type>goal</type><goal_type>n</goal_type></value></goal>
8135                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>6</event_incident_typefk><elapsed>29</elapsed><subtype>volley</subtype><player1>95078</player1><sortorder>4</sortorder><team>8178</team><id>822242</id><n>276</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>44</elapsed><player2>30937</player2><subtype>header</subtype><player1>31199</player1><sortorder>0</sortorder><team>8178</team><id>822411</id><n>294</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>80</event_incident_typefk><elapsed>83</elapsed><subtype>shot</subtype><player1>30249</player1><sortorder>1</sortorder><team>10189</team><id>822868</id><n>349</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>88</elapsed><player2>30249</player2><subtype>header</subtype><player1>2862</player1><sortorder>0</sortorder><team>10189</team><id>822914</id><n>357</n><type>goal</type><goal_type>n</goal_type></value></goal>
25467                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              None
10013                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><coordinates><value>34</value><value>7</value></coordinates><elapsed>65</elapsed><player2>36183</player2><subtype>shot</subtype><player1>93447</player1><sortorder>2</sortorder><team>9823</team><id>5101987</id><n>555</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><coordinates><value>28</value><value>8</value></coordinates><elapsed>75</elapsed><player2>116772</player2><subtype>shot</subtype><player1>30894</player1><sortorder>3</sortorder><team>9823</team><id>5102152</id><n>636</n><type>goal</type><goal_type>n</goal_type></value></goal>
8354                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>20</elapsed><player1>34267</player1><sortorder>0</sortorder><team>9810</team><id>1066740</id><n>18</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>80</elapsed><player1>30358</player1><sortorder>0</sortorder><team>8226</team><id>1067612</id><n>22</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>71</event_incident_typefk><elapsed>88</elapsed><player1>30358</player1><sortorder>0</sortorder><team>8226</team><id>1067723</id><n>23</n><type>goal</type><goal_type>n</goal_type></value></goal>
4613                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><coordinates><value>25</value><value>65</value></coordinates><elapsed>11</elapsed><player2>176300</player2><subtype>header</subtype><player1>72735</player1><sortorder>2</sortorder><team>10194</team><id>4695747</id><n>79</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><coordinates><value>28</value><value>6</value></coordinates><elapsed>28</elapsed><player2>201664</player2><subtype>shot</subtype><player1>24903</player1><sortorder>4</sortorder><team>9850</team><id>4696057</id><n>176</n><type>goal</type><goal_type>n</goal_type></value></goal>
9736                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><coordinates><value>28</value><value>8</value></coordinates><elapsed>23</elapsed><player2>258245</player2><subtype>shot</subtype><player1>192625</player1><sortorder>2</sortorder><team>9788</team><id>4124868</id><n>95</n><type>goal</type><goal_type>n</goal_type></value></goal>

In [511]:
pd.set_option('display.max_colwidth', None)
match_dataframe.dropna(subset=["goal"])


matches_with_goals = match_dataframe.dropna(subset=["goal"])
matches_with_goals["goal"].sample(20)
matches_with_goals

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
1728,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10260,10261,1,...,10.00,1.28,5.5,12.00,1.30,4.75,10.0,1.29,4.50,11.00
1729,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,9825,8659,1,...,12.00,1.25,6.0,13.00,1.22,5.50,13.0,1.22,5.00,13.00
1730,1731,1729,1729,2008/2009,1,2008-08-16 00:00:00,489044,8472,8650,0,...,1.73,5.50,3.8,1.65,5.00,3.40,1.7,4.50,3.40,1.73
1731,1732,1729,1729,2008/2009,1,2008-08-16 00:00:00,489045,8654,8528,2,...,3.75,1.90,3.5,4.35,1.91,3.25,4.0,1.91,3.25,3.80
1732,1733,1729,1729,2008/2009,1,2008-08-17 00:00:00,489046,10252,8456,4,...,3.75,1.90,3.5,4.35,1.91,3.25,4.0,1.91,3.30,3.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25944,25945,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992225,9931,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25945,25946,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992226,7896,10190,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25946,25947,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992227,10199,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25947,25948,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992228,10191,10192,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25948,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
match_dataframe.dropna(subset=["goal"])


matches_with_goals = match_dataframe.dropna(subset=["goal"])
matches_with_goals["goal"].sample(20)
matches_with_goals
import xml.etree.ElementTree as ET

def extract_goals(goal_xml):
    """
    Parse the <goal> XML string and return a list of goal events.
    Handles matches with no goals (goal_xml=None).
    """
    goal_events = []
    
    if not goal_xml or pd.isna(goal_xml):
        return goal_events  # empty list if no goals
    
    root = ET.fromstring(goal_xml)
    
    for value in root.findall("value"):
        scorer = value.find("player1").text if value.find("player1") is not None else None
        assister = value.find("player2").text if value.find("player2") is not None else None
        minute = value.find("elapsed").text if value.find("elapsed") is not None else None
        goal_type = value.find("goal_type").text if value.find("goal_type") is not None else None
        subtype = value.find("subtype").text if value.find("subtype") is not None else None
        team_id = value.find("team").text if value.find("team") is not None else None
        
        goal_events.append({
            "scorer": scorer,
            "team_api_id": team_id,  
            "assister": assister,
            # "minute": minute,
            # "goal_type": goal_type,
            # "subtype": subtype,
        })
            
        
    return goal_events


matches_with_goals["Goal Information"] = match_dataframe["goal"].apply(extract_goals)
matches_with_goals = matches_with_goals.explode("Goal Information")
matches_with_goals
goals_flat = pd.concat(
    [
        matches_with_goals.drop(columns=["Goal Information"]),
        matches_with_goals["Goal Information"].apply(pd.Series),
    ],
    axis=1
)
goals_flat
goals_flat["team_api_id"] = pd.to_numeric(goals_flat["team_api_id"])
goals_flat = pd.merge(goals_flat, team_dataframe, on="team_api_id", how="left")

assists_dataframe = goals_flat.copy()
assists_dataframe.dropna(subset=["assister"], inplace=True)
assists_dataframe
goals_flat
# #goals_flat
# assists_dataframe

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_1475/3809224125.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_with_goals["Goal Information"] = match_dataframe["goal"].apply(extract_goals)

,id_x,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,BSD,BSA,scorer,team_api_id,assister,0,id_y,team_fifa_api_id,team_long_name,team_short_name
0,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10260,10261,1,...,4.50,11.00,37799,10261.0,38807,NaN,3458.0,13.0,Newcastle United,NEW
1,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10260,10261,1,...,4.50,11.00,24148,10260.0,24154,NaN,3457.0,11.0,Manchester United,MUN
2,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,9825,8659,1,...,5.00,13.00,26181,9825.0,39297,NaN,3459.0,1.0,Arsenal,ARS
3,1731,1729,1729,2008/2009,1,2008-08-16 00:00:00,489044,8472,8650,0,...,3.40,1.73,30853,8650.0,30889,NaN,3462.0,9.0,Liverpool,LIV
4,1732,1729,1729,2008/2009,1,2008-08-16 00:00:00,489045,8654,8528,2,...,3.25,3.80,23139,8654.0,36394,NaN,3463.0,19.0,West Ham United,WHU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40968,25948,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992228,10191,10192,0,...,NaN,NaN,37554,10192.0,None,NaN,49117.0,900.0,BSC Young Boys,YB
40969,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,493418,9824.0,None,NaN,49122.0,286.0,FC Vaduz,VAD
40970,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,197757,10243.0,None,NaN,49124.0,894.0,FC Zürich,ZUR
40971,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,198082,10243.0,None,NaN,49124.0,894.0,FC Zürich,ZUR
40972,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,121080,10243.0,None,NaN,49124.0,894.0,FC Zürich,ZUR

In [183]:
goals_flat

total_goals = goals_flat.groupby("scorer")["team_long_name"].count().reset_index(name="goals")
team_count = goals_flat.groupby("scorer")["team_long_name"].nunique().reset_index(name="teams_played_for")

player_summary = total_goals.merge(team_count, on="scorer")
team_list = goals_flat.groupby("scorer")["team_long_name"].unique().reset_index(name="teams")

team_list = pd.merge(team_list, player_summary, on="scorer")
team_list.sort_values(by="goals", ascending=False)


player_assists = assists_dataframe.groupby("assister")["team_long_name"].count().reset_index(name="assists")
player_assists.sort_values(by="assists", ascending=False)

team_list.rename(columns={"scorer": "player_api_id"}, inplace=True)
player_assists.rename(columns={"assister": "player_api_id"}, inplace=True)

goals_assists = pd.merge(team_list, player_assists, on="player_api_id", how="outer").fillna(0)

goals_assists.drop(columns=["teams_played_for"], inplace=True)

goals_assists["Goals and Assists"] = goals_assists["goals"]  + goals_assists["assists"].astype("int64")

goals_assists.sort_values(by="Goals and Assists", ascending=False)

new_dataframe = player_dataframe[["player_api_id", "player_name"]]

new_dataframe["player_api_id"] = new_dataframe["player_api_id"].astype("int64")
goals_assists["player_api_id"] = goals_assists["player_api_id"].astype("int64")
new_dataframe = pd.merge(new_dataframe, goals_assists, on="player_api_id", how="left").fillna(0)


new_dataframe.sort_values(by="Goals and Assists", ascending=False).head(40)

/var/folders/kz/wkqtl4j969d5fgytvys6k_jw0000gn/T/ipykernel_1475/3478514524.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataframe["player_api_id"] = new_dataframe["player_api_id"].astype("int64")

,player_api_id,player_name,teams,goals,assists,Goals and Assists
6169,30981,Lionel Messi,[FC Barcelona],295.0,89.0,384.0
1992,30893,Cristiano Ronaldo,"[Manchester United, Real Madrid CF]",290.0,65.0,355.0
11041,35724,Zlatan Ibrahimovic,"[Paris Saint-Germain, Inter, Milan, FC Barcelona]",207.0,50.0,257.0
3932,25759,Gonzalo Higuain,"[Napoli, Real Madrid CF]",174.0,34.0,208.0
9659,37412,Sergio Aguero,"[Manchester City, Atlético Madrid]",156.0,38.0,194.0
10733,30829,Wayne Rooney,[Manchester United],135.0,58.0,193.0
6369,40636,Luis Suarez,"[Liverpool, Ajax, FC Barcelona]",136.0,56.0,192.0
2860,49677,Edinson Cavani,"[Paris Saint-Germain, Palermo, Napoli]",168.0,16.0,184.0
892,27734,Antonio Di Natale,[Udinese],156.0,20.0,176.0
9083,30843,Robin van Persie,"[Arsenal, Manchester United]",124.0,50.0,174.0
5629,26166,Karim Benzema,[Real Madrid CF],113.0,34.0,147.0
9025,93447,Robert Lewandowski,"[Borussia Dortmund, FC Bayern Munich]",124.0,18.0,142.0
2857,15403,Edin Dzeko,"[Manchester City, VfL Wolfsburg, Roma]",120.0,22.0,142.0
1578,38817,Carlos Tevez,"[Manchester United, Manchester City, Juventus]",106.0,36.0,142.0
3656,31921,Gareth Bale,"[Tottenham Hotspur, Real Madrid CF]",90.0,49.0,139.0
5440,41468,Juan Mata,"[Chelsea, Manchester United, Valencia CF]",72.0,64.0,136.0
10227,116772,Thomas Mueller,[FC Bayern Munich],94.0,40.0,134.0
1642,30613,Cesc Fabregas,"[Arsenal, Chelsea, FC Barcelona]",61.0,71.0,132.0
3540,30631,Frank Lampard,"[Chelsea, Manchester City]",89.0,42.0,131.0
566,75310,Alvaro Negredo,"[Manchester City, UD Almería, Sevilla FC, Vale...",112.0,18.0,130.0
942,33028,Aritz Aduriz,"[RCD Mallorca, Valencia CF, Athletic Club de B...",113.0,16.0,129.0
9897,31199,Stefan Kiessling,[Bayer 04 Leverkusen],112.0,13.0,125.0
9063,37506,Roberto Soldado,"[Tottenham Hotspur, Getafe CF, Valencia CF, Vi...",102.0,19.0,121.0
2410,37459,David Silva,"[Manchester City, Valencia CF]",49.0,72.0,121.0
10012,30618,Steven Gerrard,[Liverpool],71.0,47.0,118.0
2427,30909,David Villa,"[Valencia CF, FC Barcelona, Atlético Madrid]",99.0,18.0,117.0
5846,36784,Klaas Jan Huntelaar,"[FC Schalke 04, Milan, Real Madrid CF]",104.0,13.0,117.0
6810,27326,Mario Gomez,"[VfB Stuttgart, FC Bayern Munich, Fiorentina]",110.0,7.0,117.0
7316,36378,Mesut Oezil,"[Arsenal, SV Werder Bremen, Real Madrid CF]",47.0,69.0,116.0
2661,27430,Dimitar Berbatov,"[Manchester United, Fulham, AS Monaco]",86.0,30.0,116.0
3478,30714,Francesco Totti,[Roma],86.0,30.0,116.0
498,50047,Alexis Sanchez,"[Arsenal, Udinese, FC Barcelona]",89.0,26.0,115.0
948,30834,Arjen Robben,"[FC Bayern Munich, Real Madrid CF]",86.0,29.0,115.0
3331,30853,Fernando Torres,"[Liverpool, Chelsea, Milan, Atlético Madrid]",78.0,35.0,113.0
2616,19243,Diego Costa,"[Chelsea, Real Valladolid, Atlético Madrid, Ra...",97.0,16.0,113.0
3319,33030,Fernando Llorente,"[Juventus, Athletic Club de Bilbao, Sevilla FC]",99.0,13.0,112.0
6715,129944,Marco Reus,"[Borussia Mönchengladbach, Borussia Dortmund]",86.0,25.0,111.0
292,30881,Alberto Gilardino,"[Fiorentina, Genoa, Bologna, Palermo]",99.0,9.0,108.0
8611,150565,Pierre-Emerick Aubameyang,"[AS Saint-Étienne, Borussia Dortmund]",92.0,14.0,106.0
1864,25366,Claudio Pizarro,"[SV Werder Bremen, FC Bayern Munich]",92.0,14.0,106.0

In [504]:
league_dataframe[["name"]].to_dict()["name"]

league_dataframe.loc[league_dataframe["name"] == "England Premier League"]["country_id"]

1    1729
Name: country_id, dtype: int64

In [505]:
match_dataframe["season"].unique().tolist()

['2008/2009',
 '2009/2010',
 '2010/2011',
 '2011/2012',
 '2012/2013',
 '2013/2014',
 '2014/2015',
 '2015/2016']

In [455]:
match_dataframe["country_id"].describe()

count    25979.000000
mean     11738.630317
std       7553.936759
min          1.000000
25%       4769.000000
50%      10257.000000
75%      17642.000000
max      24558.000000
Name: country_id, dtype: float64

In [552]:
player_dataframe

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [ ]:
1732     <goal><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>47</elapsed><player2>23354</player2><subtype>header</subtype><player1>26165</player1><sortorder>2</sortorder><team>10252</team><id>378837</id><n>251</n><type>goal</type><goal_type>n</goal_type></value><value><comment>p</comment><stats><penalties>1</penalties></stats><event_incident_typefk>20</event_incident_typefk><elapsed>64</elapsed><player1>40198</player1><sortorder>0</sortorder><team>8456</team><id>378981</id><n>266</n><type>goal</type><goal_type>p</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>69</elapsed><player2>24658</player2><subtype>shot</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379030</id><n>270</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>406</event_incident_typefk><elapsed>74</elapsed><player2>23782</player2><subtype>header</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379074</id><n>283</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>76</elapsed><player2>23782</player2><subtype>shot</subtype><player1>23264</player1><sortorder>1</sortorder><team>10252</team><id>379095</id><n>277</n><type>goal</type><goal_type>n</goal_type></value><value><comment>n</comment><stats><goals>1</goals><shoton>1</shoton></stats><event_incident_typefk>393</event_incident_typefk><elapsed>90</elapsed><player2>45431</player2><subtype>shot</subtype><player1>46403</player1><sortorder>1</sortorder><team>8456</team><id>379250</id><n>281</n><type>goal</type><goal_type>n</goal_type></value></goal>

In [459]:
match_dataframe

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [460]:
match_dataframe.loc[match_dataframe["season"].str.contains("2012/2013")]

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
996,997,1,1,2012/2013,1,2012-07-28 00:00:00,1223976,8571,8635,1,...,1.67,5.00,3.7,1.7,NaN,NaN,NaN,4.5,3.50,1.7
997,998,1,1,2012/2013,1,2012-07-28 00:00:00,1223977,9993,9994,2,...,2.88,2.40,3.4,2.9,2.45,3.3,2.7,2.4,3.25,2.7
998,999,1,1,2012/2013,1,2012-07-28 00:00:00,1223980,9998,1773,5,...,4.50,1.80,3.6,4.5,1.75,3.7,4.2,1.8,3.50,4.0
999,1000,1,1,2012/2013,1,2012-07-29 00:00:00,1223981,9985,10000,0,...,5.50,1.70,3.7,5.0,1.67,3.6,5.0,1.7,3.50,4.5
1000,1001,1,1,2012/2013,1,2012-07-28 00:00:00,1223982,8203,9986,4,...,6.00,1.57,3.9,6.0,1.53,3.9,6.0,1.5,3.80,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25434,25435,24558,24558,2012/2013,9,2012-09-22 00:00:00,1227777,10243,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25435,25436,24558,24558,2012/2013,9,2012-09-22 00:00:00,1227778,10179,10191,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25436,25437,24558,24558,2012/2013,9,2012-09-23 00:00:00,1227779,7730,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25437,25438,24558,24558,2012/2013,9,2012-09-23 00:00:00,1227780,10190,9777,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25438,25439,24558,24558,2012/2013,9,2012-09-23 00:00:00,1227781,10192,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [461]:
country_league

       id       name_x  country_id                    name_y
0       1      Belgium           1    Belgium Jupiler League
1    1729      England        1729    England Premier League
2    4769       France        4769            France Ligue 1
3    7809      Germany        7809     Germany 1. Bundesliga
4   10257        Italy       10257             Italy Serie A
5   13274  Netherlands       13274    Netherlands Eredivisie
6   15722       Poland       15722        Poland Ekstraklasa
7   17642     Portugal       17642  Portugal Liga ZON Sagres
8   19694     Scotland       19694   Scotland Premier League
9   21518        Spain       21518           Spain LIGA BBVA
10  24558  Switzerland       24558  Switzerland Super League

In [468]:
portugal_goals = match_dataframe.loc[match_dataframe["country_id"] == 17642]["goal"]

In [474]:
portugal_goals.sample(50)

18588    None
19685    None
17727    None
19595    None
17720    None
19402    None
18310    None
19470    None
18829    None
17903    None
18681    None
18912    None
18571    None
18982    None
18191    None
17779    None
18530    None
17799    None
18661    None
18825    None
18516    None
18304    None
18292    None
18364    None
18506    None
18943    None
18399    None
18090    None
18621    None
18853    None
19545    None
19647    None
18355    None
17843    None
18541    None
18194    None
18144    None
17752    None
19478    None
19210    None
17723    None
19227    None
18610    None
19623    None
18868    None
19488    None
19040    None
19235    None
19127    None
18964    None
Name: goal, dtype: object